const folderActionTypes = {
  LOAD_FOLDERS: 'LOAD_FOLDERS',
  LOAD_FOLDERS_ERROR: 'LOAD_FOLDERS_ERROR',
  CREATE_FOLDER: 'CREATE_FOLDER',
  CREATE_FOLDER_ERROR: 'CREATE_FOLDER_ERROR'
}

export default folderActionTypes
