const groupActionTypes = {
  LOAD_GROUPS: 'LOAD_GROUPS',
  LOAD_GROUPS_ERROR: 'LOAD_GROUPS_ERROR',
  CREATE_GROUP: 'CREATE_GROUP',
  CREATE_GROUP_ERROR: 'CREATE_GROUP_ERROR'
}

export default groupActionTypes
