const actionTypes = {
  REGISTERED: 'REGISTERED',
  REGISTERED_ERROR: 'REGISTERED_ERROR',
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  LOAD_USER: 'LOAD_USER'

}

export default actionTypes
